// src/modules/dashboard/Features/MakeAdmin/MakeAdmin.vue
<script setup>
import { onMounted, ref } from 'vue';
import { getAdmin, postAdmin } from '../../api/make-admin.js';

const adminList = ref([]);
const inputData = ref({});
const isValidation = ref(false);
const isCreateModal = ref(false);

const admin_role = ref([
  {
    id: 201,
    role_name: "Admin",
  },
  {
    id: 202,
    role_name: "Modarator",
  }
]);

onMounted(() => {
  handleGetAdmin();
});

const handleCreate = () => {
  isCreateModal.value = true;
  inputData.value = {}
};

const handleGetAdmin = async () => {
  try {
    const result = await getAdmin();
    adminList.value = result.data?.list_data
  }
  catch (error) {
    console.log(error);
  }
};

const handleSubmit = async () => {
  isValidation.value = false;
  if (!inputData.value?.email ||
    !inputData.value?.role_info
  ) {
    isValidation.value = true;
    return;
  };
  const data = {
    _id: inputData.value.id || null,
    email: inputData.value?.email,
    role: inputData.value?.role_info?.role_name,
    role_id: inputData.value?.role_info?.id
  }
  try {
    const text = "Are you want to sure?"
    if (confirm(text) === true) {
      const result = await postAdmin(data)
      if (result?.status === 201) {
        alert(result.data?.message);
        isCreateModal.value = false;
        const obj = {
          _id: result.data?.id,
          email: inputData.value?.email,
          role: inputData.value?.role_info?.role_name,
          role_id: inputData.value?.role_info?.id
        };
        const index = adminList.value?.findIndex((item) => item._id == result.data?.id);
        if (index > -1) {
          adminList.value[index] = obj;
        }
        else {
          adminList.value.unshift(obj);
        }

      }
      isValidation.value = false;
      inputData.value = {};
    }

  }
  catch (error) {
    console.log(error);
  }
};

const handleCancel = () => {
  isCreateModal.value = false;
  inputData.value = {
  }
};

const handleEdit = (roleInfo) => {
  inputData.value = {
    id: roleInfo?._id,
    email: roleInfo?.email,
    role_info: admin_role.value?.find((item) => item.id == roleInfo.role_id)
  }
  isCreateModal.value = true;
};
</script>

<template>
  <div class="filter-bar d-flex flex-wrap align-items-center justify-content-between">
    <h6>Admin List</h6>
    <button @click="handleCreate" class="d-flex align-items-center">
      Create New <span class="material-icons">add</span>
    </button>
  </div>
  <table class="table table-style">
    <thead>
      <tr>
        <th>SL</th>
        <th>Role ID</th>
        <th>Email</th>
        <th>Role Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="(item, index) in adminList" :key="index">
        <td>{{ index + 1 }}</td>
        <td>{{ item?.role_id }}</td>
        <td>{{ item?.email }}</td>
        <td>{{ item?.role }}</td>
        <td>
          <span @click="handleEdit(item)" class="material-icons ms-2 cursor me-2 edit-icon">
            edit
          </span>
          <span class="material-icons ms-2 cursor delete-icon">
            delete
          </span>
        </td>
      </tr>
    </tbody>
  </table>

  <nav class="navbar bg-light fixed-top">
    <div class="container-fluid">
      <div class="offcanvas offcanvas-end create-modal" tabindex="-1" id="offcanvasNavbar"
        aria-labelledby="offcanvasNavbarLabel" :class="{ 'show': isCreateModal }"
        :style="{ visibility: isCreateModal ? 'visible' : 'hidden' }">
        <div class="offcanvas-header modal-header-style">
          <div class="d-flex align-items-center gap-3">
            <button type="button" class="btn-close" @click="handleCancel" aria-label="Close"></button>
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
              Create Admin
            </h5>
          </div>
        </div>
        <div class="offcanvas-body">
          <!-- code write here  -->
          <div class="row">
            <div class="col-md-6">
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email *</label>
                <input v-model="inputData.email" :class="{ 'is-invalid': isValidation && !inputData.email }" type="text"
                  class="form-control form-control-sm input-field-style" id="exampleInputEmail1"
                  aria-describedby="emailHelp" placeholder="Enter email">
              </div>
            </div>
            <div class="col-md-6">
              <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Select role *</label>
                <select v-model="inputData.role_info" :class="{ 'is-invalid': isValidation && !inputData.role_info }"
                  class="form-select form-select-sm input-field-style" aria-label=".form-select-sm example">
                  <option v-for="(item, index) in admin_role" :key="index" :value="item">{{ item?.role_name }}</option>
                </select>
              </div>

            </div>
          </div>
        </div>
        <div class="modal-footer d-flex justify-content-center mb-4 pt-4 modal-footer-style">
          <button @click="handleSubmit" type="submit" class="submit-btn">
            Submit
          </button>

          <button @click="handleCancel" type="cencel" class="cancel-btn ms-2">
            Cancel
          </button>
        </div>
      </div>
    </div>
  </nav>

</template>

<style scoped src="./MakeAdmin.css"></style>

// src/modules/dashboard/MakeAdmin/MakeAdmin.jsx
import axios from "axios";
import React, { useState } from "react";
import { useSelector } from "react-redux";
import { useLoaderData } from "react-router";
import Swal from "sweetalert2";

const MakeAdmin = () => {
  const userInfo = useSelector((state) => state.auth.userInfo);
  const { adminData } = useLoaderData();
  const [adminList, setAdminList] = useState(adminData?.list_data);
  const [formData, setFormData] = useState({
    _id: null,
    email: null,
    roleInfo: {},
    isEdit: false,
  });
  const [isEdit, setIsEdit] = useState(false);

  const accessList = [
    {
      role_id: 200,
      role: "Super Admin",
    },
    {
      role_id: 201,
      role: "Admin",
    },
    {
      role_id: 202,
      role: "Modarator",
    },
  ];

  const handleResetForm = () => {
    setFormData({
      _id: null,
      email: "",
      full_name: "",
      roleInfo: null,
    });
  };

  const handleSubmitAdmin = async () => {
    const confirmation = await Swal.fire({
      title: "Are you sure?",
      text: "Do you want to submit?",
      icon: "warning",
      showCancelButton: true,
      cancelButtonText: "Cancel",
      confirmButtonText: "Ok",
    });
    const data = {
      _id: isEdit ? formData._id : null,
      email: formData.email,
      role: formData.roleInfo?.role,
      role_id: formData.roleInfo?.role_id,
      user_info: userInfo?.email,
    };
    console.log("data", data);
    try {
      if (confirmation.isConfirmed) {
        const result = await axios.post(
          `${import.meta.env.VITE_PENGUIN_BACKEND_URL}/api/admin/insert-update-admin`,
          data,
        );
        if (result.data.status) {
          Swal.fire({
            icon: "success",
            title: `${result.data.message}`,
            text: `${result.data.message}`,
            confirmButtonText: "OK",
          });
          const obj = {
            _id: result.data.id,
            email: formData.email,
            role: formData.roleInfo?.role,
            role_id: formData.roleInfo?.role_id,
          };

          const index = adminList?.findIndex(
            (item) => item.id == result.data.id,
          );

          if (index > -1) {
            const updatedList = [...adminList];

            updatedList[index] = obj;

            setAdminList(updatedList);
          } else {
            setAdminList([obj, ...adminList]);
          }
          handleResetForm();
        }
        setIsEdit(false);
      }
    } catch (err) {
      console.log(err);
    }
  };

  const handleEdit = (item) => {
    setIsEdit(true);
    setFormData({
      _id: item._id,
      roleInfo: { role_id: item.role_id, role: item.role },
      email: item.email,
    });
  };

  const handleCancel = () => {
    setIsEdit(false);
    handleResetForm();
  };

  const handleRemove = async (item) => {
    const confirmation = await Swal.fire({
      title: "Are you sure?",
      text: "Do you want to submit?",
      icon: "warning",
      showCancelButton: true,
      cancelButtonText: "Cancel",
      confirmButtonText: "Ok",
    });
    try {
      if (confirmation.isConfirmed) {
        const result = await axios.delete(
          `${import.meta.env.VITE_PENGUIN_BACKEND_URL}/api/admin/delete-admin-list/${item._id}`,
        );
        if (result.data?.status) {
          const index = adminList.findIndex((list) => list._id === item._id);

          if (index !== -1) {
            const newAdminList = [...adminList];

            newAdminList.splice(index, 1);

            setAdminList(newAdminList);
          }
          Swal.fire({
            icon: "success",
            title: `${result.data.message}`,
            text: `${result.data.message}`,
            confirmButtonText: "OK",
          });
        }
      }
    } catch (err) {
      console.log(err);
    }
  };
  return (
    <div className="p-4">
      {/* 1. HEADER */}
      <header className="mb-8">
        <h1 className="font-heading text-5xl font-black uppercase tracking-tighter">
          Admin <span className="text-accent text-outline">Control</span>
        </h1>
        <p className="text-[10px] font-black uppercase tracking-[0.3em] opacity-40 mt-2">
          Assign and Manage Administrative Access
        </p>
      </header>

      {/* 2. INPUT FORM SECTION */}
      <div className="bg-base-100 border border-base-content/5 p-10 mb-6 shadow-sm">
        <h3 className="font-heading font-black uppercase tracking-widest text-xl mb-8 border-b border-base-content/5 pb-4">
          Add New Admin
        </h3>

        <form
          className="grid grid-cols-1 lg:grid-cols-4 gap-6 items-end w-full"
          onSubmit={(e) => e.preventDefault()}
        >
          {/* Email Input */}
          <div className="space-y-2 w-full">
            <label className="text-sm font-black uppercase tracking-widest opacity-50">
              User Email
            </label>
            <input
              value={formData.email}
              onChange={(e) =>
                setFormData({ ...formData, email: e.target.value })
              }
              type="email"
              placeholder="user@vortexlabs.com"
              className="w-full border-b-2 border-base-content/10 focus:border-accent outline-none py-3 text-xs font-bold transition-colors bg-transparent"
            />
          </div>

          {/* Role Dropdown */}
          <div className="space-y-2 w-full">
            <label className="text-sm font-black uppercase tracking-widest opacity-50">
              Access Level
            </label>
            <select
              value={JSON.stringify(formData.roleInfo)}
              onChange={(e) =>
                setFormData({
                  ...formData,
                  roleInfo: JSON.parse(e.target.value),
                })
              }
              className="w-full border-b-2 border-base-content/10 focus:border-accent outline-none py-3 text-xs font-bold bg-transparent uppercase tracking-wider cursor-pointer"
            >
              <option>Select Role</option>
              {accessList?.map((item, index) => (
                <option value={JSON.stringify(item)} key={index}>
                  {item?.role}
                </option>
              ))}
            </select>
          </div>

          {/* Submit Button */}
          <button
            onClick={handleSubmitAdmin}
            className="w-full bg-base-content text-base-100 px-6 py-3 font-heading font-black uppercase tracking-[0.2em] text-xs hover:bg-accent transition-all shadow-lg shadow-black/5 cursor-pointer"
          >
            {isEdit ? "Update" : "Submit"}
          </button>

          <button
            onClick={handleCancel}
            className="w-full bg-base-content text-base-100 px-6 py-3 font-heading font-black uppercase tracking-[0.2em] text-xs hover:bg-accent transition-all shadow-lg shadow-black/5 cursor-pointer"
          >
            {isEdit ? "Cancel" : "Clear"}
          </button>
        </form>
      </div>

      {/* 3. ADMIN LIST VIEW */}
      <div className="bg-base-100 border border-base-content/5 overflow-hidden">
        <div className="p-8 border-b border-base-content/5 flex justify-between items-center">
          <h2 className="font-heading text-xl font-black uppercase">
            Administrators <span className="text-accent">List</span>
          </h2>
          <span className="text-[10px] font-black opacity-30 uppercase tracking-widest">
            Total: {adminList?.length}
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="bg-base-200/50 font-heading text-[10px] uppercase tracking-widest font-black text-base-content/40">
                <th className="px-3 py-3">Super Admin</th>
                <th className="px-3 py-3">Email</th>
                <th className="px-3 py-3">Role</th>
                <th className="px-3 py-3">Created Date</th>
                <th className="px-3 py-3">Modified Date</th>
                <th className="px-3 py-5 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-black/5">
              {adminList.map((item, index) => (
                <tr
                  key={index}
                  className="group hover:bg-base-200/30 transition-colors"
                >
                  <td className="px-3 py-3">{item.user_info}</td>
                  <td className="px-3 py-3">{item.email}</td>
                  <td className="px-3 py-3">
                    <span className="inline-block border border-base-content/10 px-3 py-1 text-[9px] font-black uppercase tracking-widest rounded-full group-hover:border-accent group-hover:text-accent transition-colors">
                      {item.role}
                    </span>
                  </td>
                  <td className="px-3 py-3 text-[11px] font-bold opacity-40 uppercase">
                    {item.createdAt}
                  </td>
                  <td className="px-3 py-3 text-[11px] font-bold opacity-40 uppercase">
                    {item.modifiedAt}
                  </td>
                  <td className="px-3 py-3 text-right">
                    <span
                      onClick={() => handleEdit(item)}
                      className="material-icons cursor-pointer hover:text-blue-600 me-2"
                    >
                      edit
                    </span>
                    <span
                      onClick={() => handleRemove(item)}
                      className="material-icons cursor-pointer hover:text-red-600"
                    >
                      delete
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default MakeAdmin;
