// src/modules/dashboard/Features/AllCategory/PrentCategory/ParentCategory.vue
<script setup>
import { computed, onMounted, ref } from 'vue';
import { getParentCategory, postParentCategory, updateParentCategoryStatus, deleteParentCategory } from '@/modules/dashboard/api/categories.js';
import { useStore } from '@/store/index';


const categoryList = ref([]);
const inputData = ref({});
const isValidation = ref(false);
const isCreateModal = ref(false);
const searchKey = ref('');
const is_searchable = ref(false);
const store = useStore();

const statusList = ref([
  {
    id: 1,
    name: 'Active'
  },
  {
    id: 0,
    name: 'Inactive'
  }
]);

onMounted(() => {
  handleGetParentCategory();
});

const handleCreate = () => {
  isCreateModal.value = true;
  inputData.value = {
    status: 1
  }
};

const handleGetParentCategory = async () => {
  try {
    const result = await getParentCategory();
    categoryList.value = result.data?.list_data
  }
  catch (error) {
    console.log(error);
  }
};

const handleUpdateParentCategoryStatus = async (item) => {
  try {
    const data = { status: Number(item.status) };
    const result = await updateParentCategoryStatus(item._id, data);
    alert(result.data?.message)
  }
  catch (error) {
    console.log(error);
  };
};

const handleSubmit = async () => {
  isValidation.value = false;
  if (
    !inputData.value?.par_cat_id ||
    !inputData.value?.par_cat_name ||
    !inputData.value.status ||
    !user_email.value
  ) {
    isValidation.value = true;
    return;
  };
  const data = {
    _id: inputData.value.id || null,
    par_cat_id: Number(inputData.value?.par_cat_id),
    par_cat_name: inputData.value?.par_cat_name,
    status: inputData.value?.status,
    user_info: user_email.value,
  }
  try {
    const text = "Are you want to sure?";
    if (confirm(text) === true) {
      const result = await postParentCategory(data)
      if (result?.status === 201) {
        alert(result.data?.message);
        isCreateModal.value = false;
        const obj = {
          _id: result.data?.id,
          par_cat_id: inputData.value?.par_cat_id,
          par_cat_name: inputData.value?.par_cat_name,
          status: inputData.value?.status
        };
        const index = categoryList.value?.findIndex((item) => item._id == result.data?.id);
        if (index > -1) {
          categoryList.value[index] = obj;
        }
        else {
          categoryList.value.unshift(obj);
        }
      }
      isValidation.value = false;
      inputData.value = {};
    }
  }

  catch (error) {
    console.log(error);
  }
};

const handleCancel = () => {
  isCreateModal.value = false;
  inputData.value = {
  }
};

const handleEdit = (item) => {
  inputData.value = {
    id: item?._id,
    par_cat_id: item?.par_cat_id,
    par_cat_name: item?.par_cat_name,
    status: item?.status
  };
  isCreateModal.value = true;
};

const handleDeleteCategory = async (id) => {
  try {
    const text = "Are you want to sure?";
    if(confirm(text) === true) {
      const result = await deleteParentCategory(id);
      if(result.data?.deletedCount == 1) {
        alert(result.data?.message);
        const index = categoryList.value?.findIndex((item) => item._id === id)
          if(index !== 1) {
            categoryList.value.splice(index, 1)
          }

      }
    }
  }
  catch(error) {
    console.log(error);
  }
};

const search_func = (val) => {
  is_searchable.value = val;
};

const user_email = computed(() => store.userInfo?.email);

const filterCategories = computed(() => {
        return categoryList.value?.filter((item) =>
            Object.entries(item)
                .reduce(
                    (result, [, value]) =>
                        !(value instanceof Object) ? (result += ` ${value}`) : result,
                    ''
                )
                .toString()
                .toLowerCase()
                .includes(searchKey.value.toString().toLowerCase())
        );
    });
</script>

<template>
  <div class="filter-bar d-flex flex-wrap align-items-center justify-content-between">
    <span>Parent Category</span>
    <div class="d-flex align-items-center">
      <button @click="handleCreate" class="d-flex align-items-center">
        Create New <span class="material-icons">add</span>
      </button>
    </div>
  </div>

  <table class="table table-style">
    <thead>
      <tr>
        <th>SL</th>
        <th>Category Name

          <div class="magic-search" :class="{ active: is_searchable }" @click="search_func(true)">
                <div id="search-icon" class="search-icon">
                  <span class="material-icons">search</span>
                </div>

                <input id="search-input" v-model="searchKey" type="text" class="search-input" placeholder="Search..."
                  @blur="search_func(false)" />
              </div>
        </th>
        <th>Category ID</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="(item, index) in filterCategories" :key="index">
        <td>{{ index + 1 }}</td>
        <td>{{ item?.par_cat_name }}</td>
        <td>{{ item?.par_cat_id }}</td>
        <td>
          <div class="form-check form-switch">
            <input v-model="item.status" :value="item" :true-value="1" :false-value="0" class="form-check-input"
              type="checkbox" role="switch" id="flexSwitchCheckDisabled"
              @change="handleUpdateParentCategoryStatus(item)" />
          </div>
        </td>
        <td>
          <span @click="handleEdit(item)" class="material-icons ms-2 cursor me-2 edit-icon">
            edit
          </span>
          <span
          @click="handleDeleteCategory(item?._id)"
          class="material-icons ms-2 cursor delete-icon">
            delete
          </span>
        </td>
      </tr>
    </tbody>
  </table>

  <nav class="navbar bg-light fixed-top">
    <div class="container-fluid">
      <div class="offcanvas offcanvas-end create-modal" tabindex="-1" id="offcanvasNavbar"
        aria-labelledby="offcanvasNavbarLabel" :class="{ 'show': isCreateModal }"
        :style="{ visibility: isCreateModal ? 'visible' : 'hidden' }">
        <div class="offcanvas-header modal-header-style">
          <div class="d-flex align-items-center gap-3">
            <button type="button" class="btn-close" @click="handleCancel" aria-label="Close"></button>
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
              Create Category
            </h5>
          </div>
        </div>
        <div class="offcanvas-body">
          <!-- code write here  -->
          <div class="row">
            <div class="col-md-6">
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Category Name *</label>
                <input v-model="inputData.par_cat_name"
                  :class="{ 'is-invalid': isValidation && !inputData.par_cat_name }" type="text"
                  class="form-control form-control-sm input-field-style" id="exampleInputEmail1"
                  aria-describedby="emailHelp" placeholder="Write category name">
              </div>
            </div>
            <div class="col-md-6">
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Category ID *</label>
                <input v-model="inputData.par_cat_id" :class="{ 'is-invalid': isValidation && !inputData.par_cat_id }"
                  type="number" class="form-control form-control-sm input-field-style" id="exampleInputEmail1"
                  aria-describedby="emailHelp" placeholder="Give category id">
              </div>
            </div>
            <div class="col-md-6">
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Status *</label>
                <select v-model="inputData.status" :class="{ 'is-invalid': isValidation && !inputData.status }"
                  class="form-select form-select-sm input-field-style" aria-label=".form-select-sm example">
                  <option v-for="(item, index) in statusList" :key="index" :value="item.id">{{ item?.id }} - {{
                    item?.name }}
                  </option>
                </select>
              </div>
            </div>


          </div>
        </div>
        <div class="modal-footer d-flex justify-content-center mb-4 pt-4 modal-footer-style">
          <button @click="handleSubmit" type="submit" class="submit-btn">
            Submit
          </button>

          <button @click="handleCancel" type="cencel" class="cancel-btn ms-2">
            Cancel
          </button>
        </div>
      </div>
    </div>
  </nav>

</template>

<style scoped src="./ParentCategory.css"></style>

// src/modules/dashboard/ParentCategory/ParentCategory.jsx
import axios from "axios";
import React, { useMemo, useState } from "react";
import { useSelector } from "react-redux";
import { useLoaderData } from "react-router";
import Swal from "sweetalert2";

const ParentCategory = () => {
  const userInfo = useSelector((state) => state.auth.userInfo);
  const { parentCategoryData } = useLoaderData();
  const [categoryList, setCategoryList] = useState(
    parentCategoryData?.list_data,
  );
  console.log(parentCategoryData);
  const [formData, setFormData] = useState({
    _id: null,
    par_cat_id: "",
    par_cat_name: "",
    status: "",
    isEdit: false,
  });
  const statusList = [
    {
      value: 1,
      label: "Active",
    },
    {
      value: 0,
      label: "InActive",
    },
  ];
  const [isEdit, setIsEdit] = useState(false);
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [isInvalid, setIsInvalid] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");

  const filteredCategoryList = useMemo(() => {
    if (!searchQuery) return categoryList;
    return categoryList.filter((item) =>
      item.par_cat_name.toLowerCase().includes(searchQuery.toLowerCase()),
    );
  }, [searchQuery, categoryList]);

  const handleResetForm = () => {
    setFormData({
      _id: null,
      par_cat_id: "",
      par_cat_name: "",
      status: "",
      isEdit: false,
    });
  };

  const handleSubmit = async () => {
    setIsInvalid(false);
    if (
      !formData.par_cat_name ||
      !formData.par_cat_id ||
      !formData.status ||
      !userInfo?.email
    ) {
      setIsInvalid(true);
      Swal.fire({
        icon: "error",
        title: "Invalid or missing required fields",
        text: "Check input field",
        confirmButtonText: "OK",
      });
      return;
    }
    const confirmation = await Swal.fire({
      title: "Are you sure?",
      text: "Do you want to submit?",
      icon: "warning",
      showCancelButton: true,
      cancelButtonText: "Cancel",
      confirmButtonText: "Ok",
    });
    const data = {
      _id: isEdit ? formData._id : null,
      par_cat_id: Number(formData.par_cat_id),
      par_cat_name: formData.par_cat_name,
      status: Number(formData.status),
      user_info: userInfo?.email,
    };
    console.log("data", data);
    try {
      if (confirmation.isConfirmed) {
        const result = await axios.post(
          `${import.meta.env.VITE_PENGUIN_BACKEND_URL}/api/admin/insert-update-parent-category`,
          data,
        );
        if (result.data.status) {
          Swal.fire({
            icon: "success",
            title: `${result.data.message}`,
            text: `${result.data.message}`,
            confirmButtonText: "OK",
          });
          const obj = {
            _id: result.data.id,
            par_cat_id: Number(formData.par_cat_id),
            par_cat_name: formData.par_cat_name,
            status: formData.status,
            user_info: userInfo?.email,
          };
          handleResetForm();

          const index = categoryList?.findIndex(
            (item) => item._id == result.data.id,
          );

          if (index > -1) {
            const updatedList = [...categoryList];

            updatedList[index] = obj;

            setCategoryList(updatedList);
          } else {
            setCategoryList([obj, ...categoryList]);
          }
        }
        setIsEdit(false);
        setIsDrawerOpen(false);
      }
    } catch (err) {
      console.log(err);
    }
  };

  const handleEdit = (item) => {
    setIsEdit(true);
    setIsDrawerOpen(true);
    setFormData({
      _id: item._id,
      par_cat_id: item.par_cat_id,
      par_cat_name: item.par_cat_name,
      status: item.status,
      isEdit: true,
    });
  };

  const handleCancel = () => {
    setIsDrawerOpen(false);
    setIsEdit(false);
    handleResetForm();
  };

  const handleRemove = async (item) => {
    const confirmation = await Swal.fire({
      title: "Are you sure?",
      text: "Do you want to submit?",
      icon: "warning",
      showCancelButton: true,
      cancelButtonText: "Cancel",
      confirmButtonText: "Ok",
    });
    try {
      if (confirmation.isConfirmed) {
        const result = await axios.delete(
          `${import.meta.env.VITE_PENGUIN_BACKEND_URL}/api/admin/delete-parent-category-list/${item._id}`,
        );
        if (result.data?.status) {
          const index = categoryList.findIndex((list) => list._id === item._id);

          if (index !== -1) {
            const newcategoryList = [...categoryList];

            newcategoryList.splice(index, 1);

            setCategoryList(newcategoryList);
          }
          Swal.fire({
            icon: "success",
            title: `${result.data.message}`,
            text: `${result.data.message}`,
            confirmButtonText: "OK",
          });
        }
      }
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <div>
      <div className="p-4 min-h-screen bg-base-100 relative overflow-x-hidden">
        {/* 1. TOP BAR WITH ADD BUTTON */}
        <div className="flex flex-col md:flex-row justify-between items-end mb-12 gap-6">
          <div>
            <h1 className="font-heading text-5xl font-black uppercase  tracking-tighter text-base-content">
              Parent{" "}
              <span className="text-accent text-outline">Categories</span>
            </h1>
            <p className="text-[10px] font-black uppercase tracking-[0.3em] opacity-40 mt-2">
              Manage Store Parent Categories
            </p>
          </div>

          <button
            onClick={() => setIsDrawerOpen(true)}
            className="bg-base-content text-base-100 px-8 py-3 font-heading font-black uppercase tracking-[0.2em] text-xs hover:bg-accent transition-all flex items-center gap-3 group rounded-sm cursor-pointer"
          >
            Add New Category
            <span className="text-lg group-hover:rotate-90 transition-transform">
              +
            </span>
          </button>
        </div>

        {/* --- SEARCH BAR SECTION --- */}
        <div className="mb-8 relative max-w-md">
          <label className="text-[10px] font-black uppercase tracking-widest opacity-50 block mb-2">
            Search Categories
          </label>
          <div className="relative flex items-center">
            <span className="material-icons absolute left-0 text-sm opacity-30">
              search
            </span>
            <input
              onChange={(e) => setSearchQuery(e.target.value)}
              value={searchQuery}
              type="text"
              placeholder="FILTER BY NAME..."
              className="w-full bg-transparent border-b-2 border-base-content/10 focus:border-accent outline-none py-3 pl-7 text-xs font-bold uppercase tracking-widest transition-all placeholder:opacity-20"
            />
          </div>
        </div>
        {/* -------------------------- */}

        {/* 2. CATEGORY LIST VIEW */}
        <div className="bg-base-100 border border-base-content/5 rounded-sm shadow-sm">
          <div className="grid grid-cols-1 divide-y divide-black/5">
            {/* Header Row */}
            <div className="hidden md:grid grid-cols-4 px-8 py-4 bg-base-200/50 font-heading text-[10px] uppercase tracking-widest font-black opacity-40">
              <span className="text-left">Category Name</span>
              <span className="text-left">Category ID</span>
              <span className="text-left">Status</span>
              <span className="text-right">Actions</span>
            </div>

            {/* List Items */}
            {filteredCategoryList?.map((item, index) => (
              <div
                key={index}
                className="grid grid-cols-1 md:grid-cols-4 px-8 py-6 items-center hover:bg-base-200/30 transition-colors group"
              >
                <span className="font-heading font-bold text-sm uppercase tracking-tight group-hover:text-accent transition-colors">
                  {item.par_cat_name}
                </span>

                <span className="text-[11px] font-black opacity-60">
                  {item.par_cat_id}
                </span>
                <span className="text-[11px] font-black opacity-60">
                  {item.status}
                </span>
                <div className="flex justify-end gap-4">
                  <span
                    onClick={() => handleEdit(item)}
                    className="material-icons cursor-pointer hover:text-blue-600 me-2"
                  >
                    edit
                  </span>
                  <span
                    onClick={() => handleRemove(item)}
                    className="material-icons cursor-pointer hover:text-red-600"
                  >
                    delete
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* 3. SIDE DRAWER (OVERLAY) */}
        {/* Backdrop */}
        {isDrawerOpen && (
          <div
            className="fixed inset-0 bg-base-content/60 backdrop-blur-sm z-[100] transition-opacity"
            onClick={() => setIsDrawerOpen(false)}
          />
        )}

        {/* Drawer Content */}
        <aside
          className={`fixed top-0 right-0 h-full w-full max-w-md bg-base-100 z-[101] shadow-[-20px_0px_50px_rgba(0,0,0,0.1)] transition-transform duration-500 ease-in-out transform ${
            isDrawerOpen ? "translate-x-0" : "translate-x-full"
          }`}
        >
          <div className="h-full flex flex-col p-8">
            {/* Drawer Header */}
            <div className="flex justify-between items-center mb-12">
              <h2 className="font-heading text-3xl font-black uppercase italic tracking-tighter">
                New <span className="text-accent">Category</span>
              </h2>
              <button
                onClick={() => setIsDrawerOpen(false)}
                className="text-2xl font-black hover:text-accent rotate-45 transition-transform"
              >
                +
              </button>
            </div>

            {/* Form */}
            <div className="flex-grow space-y-10">
              <div className="space-y-2">
                <label className="text-[10px] font-black uppercase tracking-widest opacity-50">
                  Category Name <span className="text-red-600">*</span>
                </label>
                <input
                  value={formData.par_cat_name}
                  onChange={(e) =>
                    setFormData({ ...formData, par_cat_name: e.target.value })
                  }
                  type="text"
                  placeholder="Cloths"
                  className={`w-full border-b-2 ${
                    isInvalid && !formData.par_cat_name
                      ? "border-red-600"
                      : "border-base-content/10"
                  } border-base-content/10 focus:border-accent outline-none py-3 text-sm font-bold transition-colors bg-transparent placeholder:text-black/10`}
                />
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black uppercase tracking-widest opacity-50">
                  Category ID <span className="text-red-600">*</span>
                </label>
                <input
                  value={formData.par_cat_id}
                  onChange={(e) =>
                    setFormData({ ...formData, par_cat_id: e.target.value })
                  }
                  type="number"
                  placeholder="123"
                  className={`w-full border-b-2 ${
                    isInvalid && !formData.par_cat_id
                      ? "border-red-600"
                      : "border-base-content/10"
                  } border-base-content/10 focus:border-accent outline-none py-3 text-sm font-bold transition-colors bg-transparent placeholder:text-black/10`}
                />
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black uppercase tracking-widest opacity-50">
                  Status <span className="text-red-600">*</span>
                </label>
                <select
                  value={formData.status}
                  onChange={(e) =>
                    setFormData({
                      ...formData,
                      status: e.target.value,
                    })
                  }
                  className={`w-full border-b-2 ${
                    isInvalid && !formData.status
                      ? "border-red-600"
                      : "border-base-content/10"
                  } focus:border-accent outline-none py-3 text-sm font-bold bg-transparent text-base-content uppercase tracking-wider cursor-pointer`}
                >
                  {/* Mapping your country list */}
                  {statusList.map((status) => (
                    <option
                      key={status.value}
                      value={status.value}
                      className="bg-base-100 text-base-content"
                    >
                      {status.label}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            {/* Drawer Footer Actions */}
            <div className="pt-5 border-t border-base-content/5 flex justify-center gap-4">
              <button
                onClick={handleCancel}
                className="px-8 border border-base-content/10 py-3 font-heading font-black uppercase tracking-widest text-[10px] hover:bg-base-content hover:text-base-100 transition-all cursor-pointer rounded-sm"
              >
                Cancel
              </button>
              <button
                onClick={handleSubmit}
                className="px-8 bg-base-content text-base-100 py-3 font-heading font-black uppercase tracking-widest text-[10px] hover:bg-accent transition-colors cursor-pointer rounded-sm"
              >
                Save
              </button>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
};

export default ParentCategory;
